world-blacklist:
- world_nether
- world_the_end
chance: 2
debug: false
custom:
  ExampleSurprise:
    enabled: false
    lucklevel: LUCKY
    items:
      '1':
        type: DIAMOND_SWORD
        amount: 1
        displayname: '&c&lExample Sword'
        lore:
          - '&7This is the lore.'
        enchants:
          - DAMAGE_ALL:5