world-blacklist:
- world_nether
- world_the_end
chance: 2
debug: false
custom:
  ExampleSurprise1:
    enabled: false
    lucklevel: LUCKY
    items:
      '1':
        type: DIAMOND_SWORD
        amount: 1
        displayname: '&c&lExample Sword'
        lore:
          - '&7This is the lore.'
        enchants:
          - DAMAGE_ALL:5
  ExampleSurprise2:
    enabled: false
    lucklevel: LUCKY
    items:
      '1':
        slimefun_item: 'BIRTHDAY_CAKE'
        amount: 1
  ExampleSurprise3:
    enabled: false
    lucklevel: UNLUCKY
    commands:
      - 'tell {player} You''re a dead person now!'
      - 'mm mobs spawn ScaryMob 1 {world},{x},{y},{z}'