name: SlimefunLuckyBlocks
version: ${project.version}
author: mrCookieSlime
website: http://dev.bukkit.org/profiles/mrCookieSlime/bukkit-plugins/
api-version: 1.13

main: me.mrCookieSlime.SlimefunLuckyBlocks.SlimefunLuckyBlocks

depend: [Slimefun, CS-CoreLib]
